default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: parking_report_dev
  password:

test:
  <<: *default
  database: parking_report_test

production:
  <<: *default
  database: parking_report_prod
